### ISSUE TITLE
Class 'IDProviderApi' not found

### ISSUE THREAD

**Issue by bitsofmymind** [gesinn-it/IDProvider#3]
On my wiki (MediaWiki 1.31), I get this error when calling the API: `/api.php?format=json&action=paraminfo&modules=query&rawcontinue=1 Error from line 200 of /html/includes/api/ApiModuleManager.php: Class 'IDProviderApi' not found`.

It traces back to extension.json listing `    "APIListModules": {
        "idprovider": "IDProviderApi"
    },`, but there is no such class in the code.
I've removed that line and things do work better. `api.php?action=idprovider-increment&prefix=Issue_&padding=8&skipUniqueTest=true` gives out `Wikimedia\\Rdbms\\Database::begin: Implicit transaction already active (from Wikimedia\\Rdbms\\Database::query (LCStoreDB::get)).`, but `api.php?action=idprovider-random&type=fakeid` is ok.

**Comment by gesinn-it** [comment]
Thanks for reporting that issue. It's safe to remove

```
"APIListModules": {
        "idprovider": "IDProviderApi"
},
```

from extension.json

On MW 1.27, both api calls work as expected. I'll check with 1.31...

**Comment by gesinn-it** [comment]
I can reproduce your issue on MW 1.31. It seems that the DB transaction handling has changed in MW 1.31.

See also: https://www.mediawiki.org/wiki/Manual_talk:Database_access#Lock_contention_on_MW_1.31._causes_%22Wikimedia\\Rdbms\\Database::begin:_Implicit_transaction_already_active%22
