### ISSUE TITLE
Fix Declaration of IDProviderFunctionsTest::setUp()

### ISSUE THREAD

**Issue by gesinn-it-gea** [gesinn-it/IDProvider#7]
Fatal error: Declaration of IDProviderFunctionsTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /var/www/html/extensions/IDProvider/tests/phpunit/IDProviderFunctionsTest.php on line 9

**Comment by gesinn-it** [comment]
closed via #9
